version: "3.3"
services:

  postgres:
    image: postgres:12.1
    container_name: hotel_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotel
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: hotel_backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: hotel_frontend
    ports:
      - "8080:80"
    restart: always
