"""Adding games.

Revision ID: 9479ca2c182a
Revises: 84bd761bd504
Create Date: 2022-12-29 20:20:01.283504

"""
import flask_authorize
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9479ca2c182a'
down_revision = '84bd761bd504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('other_permissions', flask_authorize.mixins.PipedList(), nullable=True),
    sa.Column('owner_id', postgresql.UUID, nullable=True),
    sa.Column('owner_permissions', flask_authorize.mixins.PipedList(), nullable=True),
    sa.Column('group_id', postgresql.UUID, nullable=True),
    sa.Column('group_permissions', flask_authorize.mixins.PipedList(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_name'), ['name'], unique=False)

    op.create_table('game_user',
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('game_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_user')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_name'))

    op.drop_table('games')
    # ### end Alembic commands ###
